Add missing groups from openSUSE:Package_group_guidelines
rpm-software-management/spec-cleaner pull request #318
Opened 2023-11-16 17:24 UTC by marcosbc

The list of allowed package groups is outdated with respect to [openSUSE:Package_group_guidelines](https://en.opensuse.org/openSUSE:Package_group_guidelines), so I sent this PR updating them.

> NOTE: To generate the changes in this PR, I executed the following commands:
>
> ```shell
> cd spec-cleaner/data
> echo '# Taken from https://en.opensuse.org/openSUSE:Package_group_guidelines' > allowed_groups.txt
> curl -s https://en.opensuse.org/openSUSE:Package_group_guidelines | grep -Eo '^[^ ]+<tt>.*</tt>' | sed -E -e 's/^[^ ]+<tt>//g' -e 's/<\/tt>.*//g' >> allowed_groups.txt
> ```

Fixes #317

2023-11-16 21:58 UTC, mcepl commented
Whole `Group:` tag is completely obsolete. See for example the discussion on https://marc.info/?l=opensuse-factory&m=152759073025012&w=2 The page on Wiki should be removed.

2023-11-16 21:59 UTC, mcepl requested changes
Whole `Group:` tag is completely obsolete. See for example the discussion on https://marc.info/?l=opensuse-factory&m=152759073025012&w=2 The page on Wiki should be removed.

2023-11-17 12:08 UTC, marcosbc commented
Hi @mcepl, the default configuration for Open Build Service currently warns if this section is missing, are you sure that it is obsolete? For instance:

```
[    2s] RPMLINT report:
[    2s] ===============
[    2s] hello-world.aarch64: W: non-standard-group Unspecified
[    2s] hello-world.src: W: non-standard-group Unspecified
[    2s] The value of the Group tag in the package is not valid.  Valid groups are:
[    2s] "Amusements/Games/3D/Other", "Amusements/Games/3D/Race",
[    2s] (...)
[    2s] "System/X11/Terminals", "System/X11/Utilities", "System/YaST".
[    2s]
[    2s] 2 packages and 0 specfiles checked; 0 errors, 2 warnings.
[    2s]
[    2s]
[    2s] localhost.localdomain finished "build hello-world.spec" at Fri Nov 17 02:55:47 UTC 2023.
```

[Here](https://build.opensuse.org/package/show/home:mbjoerkelund:spec-cleaner-318/hello-world) can you find an example of such errors (go to the "RPM Lint" section to see the warnings).

2023-11-18 21:13 UTC, mcepl commented
On Fri Nov 17, 2023 at 1:09 PM CET, Marcos Bjoerkelund wrote:
> Hi @mcepl, the default configuration for Open Build Service currently warns if this section is missing, are you sure that it is obsolete? For instance:

Which distro? I don’t see anything like that for Tumbleweed or reasoably recent (and supported) SLE/Leap distros.

Matěj

-- 
http://matej.ceplovi.cz/blog/, @***@***.***
GPG Finger: 3C76 A027 CA45 AD70 98B5  BC1D 7920 5802 880B C9D8
 
Revenge is the misguided attempt to transform shame and pain
into pride.
  -- Oceanbreeze7 in the summary of the story “Antithesis”
     (on FFN)

2023-11-20 09:44 UTC, marcosbc commented
@mcepl Please have a look at this project in OBS I created as an example for this issue: [home:mbjoerkelund:spec-cleaner-318/hello-world](https://build.opensuse.org/package/show/home:mbjoerkelund:spec-cleaner-318/hello-world)

I updated the project to build for SLE, openSUSE Leap and Tumbleweed. You can see that the RPMlint warning appears both for SLE and openSUSE Leap, but not for Tumbleweed, so I think this is still applicable.

2023-11-20 12:11 UTC, mcepl commented
Then ask for the upgrade of rpmlint in SLE/Leap, but I will do nothing to support the idea of groups.

2023-11-20 15:25 UTC, closed without merging

2023-11-20 15:25 UTC, marcosbc commented
It seems like the `Group:` tag is still required for SLE and Leap, but this change has been rejected altogether, so I'm going to close this MR.